# Generated by Django 5.1.1 on 2024-10-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ehr", "0002_alter_patient_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording", models.CharField(max_length=200)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ehr.patient",
                    ),
                ),
            ],
        ),
    ]
