# Generated by Django 5.1.1 on 2024-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=25),
        ),
    ]
