# Generated by Django 5.1.1 on 2024-10-08 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0003_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("name", "age", "phone")},
        ),
    ]
