# Generated by Django 5.1.1 on 2024-10-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0004_alter_patient_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_sid", models.CharField(max_length=100, unique=True)),
                ("initial_choice", models.CharField(max_length=1)),
                ("user_identification", models.CharField(max_length=1)),
                ("ehr_id", models.CharField(blank=True, max_length=50)),
                ("symptoms", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ehr.patient"
                    ),
                ),
            ],
        ),
    ]
